version: "3.8"

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: unless-stopped
    volumes:
      - ./zabbix_data/server:/var/lib/zabbix  # Store server data in ./zabbix_data/server
      - ./zabbix_data/alertscripts:/usr/lib/zabbix/alertscripts # Store Alert scripts
      - ./zabbix_data/externalscripts:/usr/lib/zabbix/externalscripts # External Scripts
      - ./zabbix_data/modules:/var/lib/zabbix/modules # Modules
      - ./zabbix_data/enc:/var/lib/zabbix/enc #Encrypted Files
      - ./zabbix_data/ssh_keys:/var/lib/zabbix/ssh_keys #SSH Keys
      - ./zabbix_data/ssl/certs:/var/lib/zabbix/ssl/certs #Client Certificates
      - ./zabbix_data/ssl/keys:/var/lib/zabbix/ssl/keys #SSL Keys
      - ./zabbix_data/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca #CA files
      - ./zabbix_data/snmptraps:/var/lib/zabbix/snmptraps #SNMP Traps
      - ./zabbix_data/mibs:/var/lib/zabbix/mibs #MIB files
      - ./zabbix_data/export:/var/lib/zabbix/export #Real time exports

    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      ZBX_DEBUGLEVEL: 3
    depends_on:
      - mysql

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Riga"
    depends_on:
      - zabbix-server
      - mysql
    volumes:
      - ./zabbix_data/nginx/ssl:/etc/ssl/nginx #NGINX SSL
      - ./zabbix_data/web/certs:/etc/zabbix/web/certs #Web certs

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./zabbix_data/mysql:/var/lib/mysql  # Store MySQL data in ./zabbix_data/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    ports:
      - "3306:3306"
